---
- name: Install nginx
  hosts: my-server
  remote_user: ubuntu
  bocome: yes
  vars:
    ansible_ssh_private_key_file: "/home/ubuntu/hostserverkey.pem"
  roles:
    - jenkins
    - nginx

        