---
- name: Install nginx
  hosts: my-server
  remote_user: ubuntu
  bocome: yes
  vars:
    ansible_ssh_private_key_file: "/home/ubuntu/hostkey.pem"
  tasks:
    - name: Update package
      apt: 
        update_cache: yes
    - name: Install nginx
      apt: 
        name: nginx
        state: present
    
    - name: Enable nginx
      service: 
        name: nginx
        state: started
        enabled: yes
        
        