---
- name: package
  shell: |
    curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee \
      /usr/share/keyrings/jenkins-keyring.asc > /dev/null
    echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
      https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
      /etc/apt/sources.list.d/jenkins.list > /dev/null
  
- name: Install Openjdk
  apt:
    name: openjdk-11-jdk
    update_cache: yes
    state: present

- name: Install Jenkins
  apt:
    name: jenkins
    state: present

- name: show initialpassword
  command: cat /var/lib/jenkins/secrets/anitalAdminPassword
  register: command_output

- name: Print passowrd
  debug: msg="{{command_prompt}}"
